baseURL = "https://pierremalherbe.com/"
languageCode = "fr"
title = "Pierre Malherbe"
theme = "hugo-uilite"
paginate= 10
enableGitInfo = true

[author]
  name = "Pierre Malherbe"

[params]
   author = "Pierre Malherbe"
   description = "DevOps passionné sur le secteur de Lille. "
